# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  workingDirectory: SampleService/SampleService
- script: docker build -t /sampleservice .
  displayName: 'docker image build'
  workingDirectory: SampleService/SampleService
- script: |
    docker login -u example -p example
    docker push example/sampleservice
  displayName: 'push docker image to dockerhub'
  workingDirectory: SampleService/SampleService
- task: HelmInstaller@0
  inputs:
    helmVersion: '2.9.1'
    installKubectl: false
- task: HelmDeploy@0
  inputs:
    connectionType: 'None'
    command: 'package'
    chartType: 'filepath'
    chartPath: '$(Build.SourcesDirectory)/SampleService/SampleService/sampleservice'
- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: 'SampleService/SampleService/*.tgz'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop

